import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-fleet-fuel-card-toll-leakage-recovery",
  "engine": "recovery",
  "title": "Fleet Fuel Card & Toll Leakage Recovery",
  "shortTitle": "Fleet Spend Recovery",
  "tagline": "Detect fraud, duplicate tolls, contract errors, and vehicle-level spend leakage",
  "industry": "Fleet Expense Assurance",
  "uiPort": 4567,
  "apiPort": 5567,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Fuel and toll leakage stopped and recovered with vehicle, trip, and contract evidence",
  "valueNarrative": "Correlate cards, drivers, vehicles, telematics, odometers, fuel transactions, toll gantries, trips, invoices, and rebates.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Fuel and toll charges",
    "expectedLabel": "Trip-supported spend",
    "varianceLabel": "Potential fleet recovery",
    "direction": "actual-minus-expected",
    "finding": "Card, vehicle, trip, price, rebate, and toll evidence indicate unsupported fleet expense.",
    "actions": [
      "Match transactions to assigned driver, vehicle, and trip",
      "Validate volume, grade, location, timing, toll, and contract price",
      "Dispute fraud, duplicates, and billing exceptions",
      "Reconcile refund and enforce preventive controls"
    ]
  }
},[
feature("card-driver-and-vehicle-registry","FSR01","Card driver and vehicle registry","Reconcile card driver and vehicle registry using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed card driver and vehicle registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("fuel-transaction-ingestion","FSR02","Fuel transaction ingestion","Reconcile fuel transaction ingestion using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed fuel transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("telematics-and-odometer-matching","FSR03","Telematics and odometer matching","Reconcile telematics and odometer matching using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed telematics and odometer matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("impossible-transaction-detection","FSR04","Impossible transaction detection","Reconcile impossible transaction detection using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed impossible transaction detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("fuel-volume-and-tank-capacity-control","FSR05","Fuel volume and tank-capacity control","Reconcile fuel volume and tank-capacity control using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed fuel volume and tank-capacity control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("fuel-grade-and-product-validation","FSR06","Fuel grade and product validation","Reconcile fuel grade and product validation using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed fuel grade and product validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("price-and-discount-audit","FSR07","Price and discount audit","Reconcile price and discount audit using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed price and discount audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("rebate-reconciliation","FSR08","Rebate reconciliation","Reconcile rebate reconciliation using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed rebate reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("toll-transaction-ingestion","FSR09","Toll transaction ingestion","Reconcile toll transaction ingestion using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed toll transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("duplicate-and-impossible-toll-detection","FSR10","Duplicate and impossible toll detection","Reconcile duplicate and impossible toll detection using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed duplicate and impossible toll detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("rental-and-replacement-vehicle-control","FSR11","Rental and replacement vehicle control","Reconcile rental and replacement vehicle control using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed rental and replacement vehicle control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("fraud-case-workbench","FSR12","Fraud case workbench","Reconcile fraud case workbench using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed fraud case workbench decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("vendor-dispute-and-recovery","FSR13","Vendor dispute and recovery","Reconcile vendor dispute and recovery using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed vendor dispute and recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("card-control-and-preventive-alerts","FSR14","Card control and preventive alerts","Reconcile card control and preventive alerts using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed card control and preventive alerts decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]}),
feature("vehicle-vendor-and-route-analytics","FSR15","Vehicle vendor and route analytics","Reconcile vehicle vendor and route analytics using card assignments, driver and vehicle registries, telematics, odometers, fuel prices, toll gantries, trips, invoices, and rebates.","Produce a governed vehicle vendor and route analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","Fuel / Toll Vendor","text","National Fleet Network"],["vehiclePeriod","Vehicle / Period","text","TRK-884 / 2026-06"],["chargedAmount","Charged Amount","currency",274000],["supportedAmount","Supported Fleet Spend","currency",231500]],{amountField:"chargedAmount",subjects:["Long-haul tractor fleet","Service van fleet","Municipal fleet","Rental vehicle program","Regional delivery fleet"]})
]);
